<?php
require_once('Database.php');
require_once('Clanok.php');
require_once('Menu.php');
require_once('Page.php');
require_once('SoC_clanok.php');
require_once('Functions.php');
require_once('Users.php');
require_once('Update_clanok.php');
?>